FROM quay.io/aptible/ubuntu:18.04

# Create user early to ensure consistent UID
ENV ES_USER elasticsearch
ENV ES_GROUP elasticsearch
RUN getent group "$ES_GROUP" || groupadd -r "$ES_GROUP"
RUN getent passwd "$ES_USER" || useradd -r -g "$ES_GROUP" "$ES_USER"

# Install utilities we'll need
RUN apt-install software-properties-common apache2-utils sudo curl

# Install Elasticsearch and backup plugin.
ENV DOWNLOAD_URL <%= ENV.fetch 'DOWNLOAD_URL' %>
ENV ES_VERSION <%= ENV.fetch 'ES_VERSION' %>
ENV ES_SHA512SUM <%= ENV.fetch 'ES_SHA512SUM' %>

# Plugin wrapper for ES compatibility
ADD bin/plugin-install-wrapper /usr/bin/plugin-install-wrapper

RUN cd /tmp \
 && curl -fsSL -o "elasticsearch-${ES_VERSION}.tar.gz" "${DOWNLOAD_URL}" \
 && echo "${ES_SHA512SUM}  elasticsearch-${ES_VERSION}.tar.gz" | sha512sum -c - \
 && tar xf "elasticsearch-${ES_VERSION}.tar.gz" \
 && rm "elasticsearch-${ES_VERSION}.tar.gz" \
 && mv "elasticsearch-${ES_VERSION}" /elasticsearch \
 && chown -R "${ES_USER}:${ES_GROUP}" "/elasticsearch/config" "/elasticsearch/logs" "/elasticsearch/jdk" \
 && plugin-install-wrapper repository-s3

# Configuration templates
ADD templates/elasticsearch.yml.template /elasticsearch/config/elasticsearch.yml.template
RUN rm /elasticsearch/config/elasticsearch.yml

# Additional wrappers
ADD bin/cluster-wrapper /usr/bin/cluster-wrapper
ADD bin/elasticsearch-wrapper /usr/bin/elasticsearch-wrapper

ADD bin/run-database.sh /usr/bin/
ADD bin/utilities.sh /usr/bin/

ENV DATA_DIRECTORY /var/db
ENV SSL_DIRECTORY /var/db/ssl

VOLUME ["$DATA_DIRECTORY"]

# Integration tests
ADD test /tmp/test

EXPOSE 9200

ENTRYPOINT ["run-database.sh"]
